version: '3'
services:
  front:
    build: .
    container_name: load-balancer
    ports:
      - '3030:3030'
    command: --backends "http://web:80"
  web:
    image: strm/helloworld-http
    deploy:
      replicas: 3
